### ISSUE TITLE
Don't send exceptions asynchronously by default

### ISSUE THREAD

**Issue by gmartsenkov** [honeybadger-io/honeybadger-crystal#22]
It looks like the `notify` function is calling a spawn by default.
I don't think that library should decide this, here's an example where a notification fails to be sent:
```crystal
# main.cr

begin 
  raise "Error"
rescue exception
  Honeybadger.notify(exception)
end
```
Because the above `notify` call spawns a new fiber, it'll not get the chance to execute because by the time we get to it the application has terminated. My suggestion is to not send the request to honeybadger in a `spawn`, otherwise i have to call `sleep X` and hope the notification gets send

https://github.com/honeybadger-io/honeybadger-crystal/blob/bd53b99a9af88eb4db5c8df850031f0a27211bdc/src/honeybadger.cr#L11

I don't mind making a PR for this if needed. We can rename the existing `notify` to `notify_async` and introduce a normal `notify` without the fiber spawn

**Comment by robacarp** [comment]
@gmartsenkov Hey thank you for stopping by. Your example is correct. I think the default behavior should be as it is -- most applications are expected to be long running and blocking the execution cycle in order to send an exception report is not what I want as the default behavior.

There probably is room for a synchronous version of #notify, but I'm not sure what the Honeybadger spec recommends. @joshuap any thoughts? Perhaps Honeybadger#notify should take an async boolean?

**Comment by joshuap** [comment]
> @gmartsenkov Hey thank you for stopping by. Your example is correct. I think the default behavior should be as it is -- most applications are expected to be long running and blocking the execution cycle in order to send an exception report is not what I want as the default behavior.
> 
> There probably is room for a synchronous version of #notify, but I'm not sure what the Honeybadger spec recommends. @joshuap any thoughts? Perhaps Honeybadger#notify should take an async boolean?

In the Ruby gem, we have the `sync: true` option (defaults to `false`): https://github.com/honeybadger-io/honeybadger-ruby/blob/e6c3bd80463eebd627fd5c5e160a0c5576034999/lib/honeybadger/agent.rb#L109
