### ISSUE TITLE
Context API

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-crystal#4]
The client should have a **public** `context()` method that stores a data hash which will be added to notices. There should also be a public `clear()` method to reset the context to the default (`{}`).

- Data should be stored [local to the current thread](https://www.notion.so/Client-Library-Spec-aa891332f7874196aa0695b6d38dca66)
- Data should be sanitized, but not filtered](https://www.notion.so/Client-Library-Spec-aa891332f7874196aa0695b6d38dca66)

```crystal
# Adding context:
Honeybadger.context({ foo: "bar" })

# Clearing context:
Honeybadger.clear()
```

The client should also support passing local context into `Honeybadger.notify` (and similar methods) as an option:

```crystal
Honeybadger.notify(exception, {
  context: {
    user_id: 1
  }
})
```

When global context also exists, the local context should take precedence.

### Examples

- [`Honeybadger.context` in Ruby](https://github.com/honeybadger-io/honeybadger-ruby/blob/2d24a36f5f560c4234f22f59153c80f32e4ce177/lib/honeybadger/agent.rb#L253)
- [`Honeybadger.clear` in Ruby](https://github.com/honeybadger-io/honeybadger-ruby/blob/2d24a36f5f560c4234f22f59153c80f32e4ce177/lib/honeybadger/agent.rb#L259)

### Resources

- [Client Library Spec](https://www.notion.so/honeybadger/Client-Library-Spec-aa891332f7874196aa0695b6d38dca66#d9a1892930694580a9f41eebb99c22bd)
- [Honeybadger Documentation](https://docs.honeybadger.io)
- [Exceptions API Documentation](https://docs.honeybadger.io/api/exceptions.html)
- [Notices JSON Schema](https://github.com/honeybadger-io/honeybadger-schemas/blob/master/exceptions/v1/notices.json)

**Comment by jgaskins** [comment]
I'm working on a Datadog-friendly logger for [my Datadog shard](https://github.com/jgaskins/datadog) to provide faceted log search and noticed that the [stdlib `Log` class supports fiber-local context](https://crystal-lang.org/api/1.0.0/Log/Context.html). It seems like it could be worthwhile to lean on when implementing this.

Where my mind's going with this is that if you're using both Datadog and Honeybadger, like I am, or any other combination of libraries that provide insights into an application, they can all share the same context source. For example, if my application has this method somewhere to get the current user based on session data:

```crystal
def current_user : User?
  if user_id = session["user_id"]?
    user = UserQuery.new.find_by_id(user_id)
    Log.context.set user: { id: user.id, username: user.username }
  end

  user
end
```

The `Log.context.set` call will assign the user's id and username to the `user` context variable. This lets an application pass the same data to both Honeybadger and Datadog in a single method call. And the `Honeybadger::Payload` could then just incorporate `Log.context.metadata` into its `to_json` method

We don't need to worry about collisions as mentioned in #17 because it's all fiber-local and the Crystal core team has already figured all of that out for us. We get those guarantees for free.

There are two things that can make this a bit wonky, though:

1. It ties error-handling context to a logging API, which isn't very intuitive
2. Using fiber-scoped state gets weird if you spawn your own fibers inside a web request to handle things concurrently
   - For example, if you fire off a bunch of API calls concurrently in multiple fibers to avoid running them serially and improve latency
   - Child fibers won't pass their context back to the parent fiber if an exception is raised

**Comment by joshuap** [comment]
@jgaskins love the ideas, thanks!

@robacarp I wonder how `Log.context.set()` works—maybe we could do something similar for `Honeybadger.context()`?

Regarding sending `Log.context` to Honeybadger, I think that could be convenient, especially if we ever add an option to report warnings/errors from the logger (we support that feature in a few languages, although not in Ruby).

**Comment by robacarp** [comment]
I looked into it after @jgaskins commented here and `Log.context.set` boils down to [a monkeypatch](https://github.com/crystal-lang/crystal/blob/6a3f6b1e89be89dbe32a66a11da92d35e7790977/src/log/metadata.cr#L222-L229) on Fiber. It's a trivial patch and easy to reproduce, but may not be the kind of code that we want here -- on a dependency I try to keep monkeypatching core systems to an absolute zero because of the unintended consequences.

The unintended consequences here are probably minimal. As far as I can see. But I suppose that's what makes them unintended. :)

@joshuap monkeypatching in crystal works pretty much like it does in Ruby. Is that a risk/reward worth taking? Or too much?

**Comment by joshuap** [comment]
> @joshuap monkeypatching in crystal works pretty much like it does in Ruby. Is that a risk/reward worth taking? Or too much?

If it's the best practical option to get use the functionality we need, then I'd say go for it. 😁 I prefer not to patch core language stuff if possible, but the fact that Crystal's core logger does this makes me feel better about it (assuming we aren't interfering too much). I would opt for the mutex approach if they are equivalent.

**Comment by stephendolan** [comment]
@robacarp Like we discussed in Discord, I think this is unfortunately another prerequisite for using Honeybadger most elegantly with a framework like Lucky.

This will enable the addition of context (like user information) in an action like `errors/show.cr` while still leaving the Honeybadger middleware in place. I'm happy to test a WIP branch when it's ready to help provide feedback!

Thanks for all the great work on this shard. It's really coming together!
